steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        apt-get update && apt-get install -y curl jq

        echo "REVISION_ID: $REVISION_ID"

        PR_INFO=$(curl -s -H "Authorization: token $$GITHUB_TOKEN" \
          "https://api.github.com/repos/$REPO_FULL_NAME/commits/$REVISION_ID/pulls")

        echo "PR_INFO: $$PR_INFO"

        PR_NUMBER=$(echo "$$PR_INFO" | jq -r '.[0].number')
        SERVICE_NAME="$REPO_NAME-pr-$$PR_NUMBER"

        echo "🧹 Deleting Cloud Run service: $$PR_NUMBER"
        echo "🧹 Deleting Cloud Run service: $$SERVICE_NAME"

        gcloud run services delete "$$SERVICE_NAME" \
          --region="$LOCATION" \
          --platform=managed \
          --quiet || echo "⚠️ Service $$SERVICE_NAME not found or already deleted"
    secretEnv: ["GITHUB_TOKEN"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/gh-token/versions/latest
      env: "GITHUB_TOKEN"

options:
  logging: CLOUD_LOGGING_ONLY
