steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/fifty-fifty-app:pr-$BUILD_ID',
        '.'
      ]
  # Push image to Artifact Registry / GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/fifty-fifty-app:pr-$BUILD_ID'
      ]
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'fifty-fifty-pr-$BUILD_ID',
        '--image', 'gcr.io/$PROJECT_ID/fifty-fifty-app:pr-$BUILD_ID',
        '--region', 'asia-northeast1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY