steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/fifty-fifty-app:pr-$BUILD_ID',
        '.'
      ]
  # Push image to Artifact Registry / GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/fifty-fifty-app:pr-$BUILD_ID'
      ]
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'fifty-fifty-pr-$BUILD_ID',
        '--image', 'gcr.io/$PROJECT_ID/fifty-fifty-app:pr-$BUILD_ID',
        '--region', 'asia-northeast1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
  # Comment the deployed URL on the GitHub Pull Request
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        DEPLOY_URL=$(gcloud run services describe fifty-fifty-pr-$BUILD_ID \
          --region=asia-northeast1 \
          --format="value(status.url)")

        echo "✅ Cloud Run URL: $DEPLOY_URL"

        curl -X POST \
          -H "Authorization: token $$GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"🚀 PR Preview deployed to: $DEPLOY_URL\"}" \
          "https://api.github.com/repos/$REPO_FULL_NAME/issues/$_PR_NUMBER/comments"
    secretEnv: ['GITHUB_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/gh-token/versions/latest
      env: 'GITHUB_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY