name: "Publish Docker Image"
description: "Publish Docker Image to Artifact Registry"

inputs:
  project_id:
    description: "Google Cloud Project ID"
    required: true
  service_account:
    description: "Google Cloud Service Account"
    required: true
  workload_identity_provider:
    description: "Workload Identity Provider"
    required: true
  region:
    description: "Google Cloud Region"
    required: true
  image_tags:
    description: "Docker image tags"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      id: auth
      with:
        project_id: ${{ inputs.project_id }}
        service_account: ${{ inputs.service_account }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: Docker Auth
      uses: docker/login-action@v3
      with:
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.auth_token }}
        registry: ${{ inputs.region }}-docker.pkg.dev

    - name: Configure docker to use the gcloud cli
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Container
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ inputs.image_tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
