name: "Setup Node.js and pnpm"
description: "Sets up Node.js, pnpm and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash
