name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Restore storybook-static cache
        id: storybook-cache
        uses: actions/cache@v4
        with:
          path: storybook-static
          key: ${{ runner.os }}-storybook-${{ hashFiles('**/*.stories.@(js|jsx|ts|tsx|mdx)', 'package.json', 'pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-storybook-

      - name: Build Storybook (if not cached)
        if: steps.storybook-cache.outputs.cache-hit != 'true'
        run: pnpm build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages