name: "Terraform Preview for PR"

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state != 'closed'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
          registry: ${{ secrets.REGION }}-docker.pkg.dev

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        id: build-image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}/pr-${{ github.event.pull_request.number }}:${{ github.sha }}

      - name: Create PR Terraform Files
        working-directory: ./terraform/envs
        run: |
          echo 'terraform {
            backend "gcs" {
              bucket = "terraform-state-natural-nimbus"
              prefix = "envs/pr-${{ github.event.pull_request.number }}"
            }
          }' > pr/backend.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.12.1'

      - name: Terraform Init
        working-directory: ./terraform/envs/prod
        run: terraform init

      - name: Terraform Plan & Apply
        working-directory: ./terraform/envs/prod
        env:
          TF_VAR_project: ${{ secrets.PROJECT_ID }}
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_service_name: ${{ secrets.SERVICE }}-pr-${{ github.event.pull_request.number }}
          TF_VAR_image: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}/pr-${{ github.event.pull_request.number }}:${{ github.sha }}
        run: terraform apply -auto-approve

      - name: Comment Preview URL on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 Preview deployed to:
            https://fifty-fifty-pr-${{ github.event.pull_request.number }}.a.run.app

  # destroy:
  #   if: github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3

  #     - name: Terraform Init
  #       run: terraform init -backend-config="bucket=my-bucket"

  #     - name: Terraform Destroy
  #       run: |
  #         terraform destroy -auto-approve \
  #           -var="project=my-gcp-project" \
  #           -var="region=asia-northeast1" \
  #           -var="service_name=fifty-fifty-pr-${{ github.event.pull_request.number }}" \
  #           -var="image=..."