name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  ENV: prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/publish
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          region: ${{ secrets.REGION }}
          image_tags: |
            ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}/${{ env.ENV }}:${{ github.sha }}
            ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}/${{ env.ENV }}:latest

      - uses: ./.github/actions/terraform-apply
        with:
          working-directory: ./terraform/envs/prod
          project_id: ${{ secrets.PROJECT_ID }}
          region: ${{ secrets.REGION }}
          service_name: ${{ secrets.SERVICE }}
          image: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}/${{ env.ENV }}:${{ github.sha }}