name: PR Closed Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    name: Cleanup Preview Environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Create PR Terraform Files
        working-directory: ./terraform/envs
        run: |
          echo 'terraform {
            backend "gcs" {
              bucket = "terraform-state-natural-nimbus-pr"
              prefix = "envs/pr-${{ github.event.pull_request.number }}"
            }
          }' > pr/backend.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.12.1'

      - name: Terraform Init
        working-directory: ./terraform/envs/pr
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform/envs/pr
        env:
          TF_VAR_project: ${{ secrets.PROJECT_ID }}
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_service_name: ${{ secrets.SERVICE }}
          TF_VAR_pr_number: ${{ github.event.pull_request.number }}
          TF_VAR_image: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}-pr/pr-${{ github.event.pull_request.number }}:${{ github.sha }}
        run: terraform destroy -auto-approve

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Delete tfstate from GCS
        run: |
          gsutil rm -r gs://terraform-state-natural-nimbus-pr/envs/pr-${{ github.event.pull_request.number }}/